name: end-to-end

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install browsers
        run: |
          playwright install --with-deps

      - name: Run tests
        run: |
          cp .env.sample .env

          if [[ $PYTEST_ENABLE_TERMINAL == "true" ]]; then
            python main.py
          else
            python main.py -p no:terminal
          fi
        env:
          PYTEST_ENABLE_TERMINAL: ${{ vars.PYTEST_ENABLE_TERMINAL }}
          OGRU_USER_LOGIN: ${{ vars.OGRU_USER_LOGIN }}
          OGRU_USER_PASSWORD: ${{ secrets.OGRU_USER_PASSWORD }}

      - name: Get history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Latest alias
        run: |
          _alias_dir="latest"
          _alias_file="index.html"
          _alias_path="${_alias_dir}/${_alias_file}"
          mkdir -p "${_alias_dir}"
          touch "${_alias_path}"
          echo "<!DOCTYPE html><meta charset=\"utf-8\"><meta http-equiv=\"refresh\" content=\"0; URL=https://s0nought.github.io/ogru-tests/${GITHUB_RUN_NUMBER}/index.html\">" >> "${_alias_path}"
          echo "<meta http-equiv=\"Pragma\" content=\"no-cache\"><meta http-equiv=\"Expires\" content=\"0\">" >> "${_alias_path}"

      - name: Generate report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20

      - name: Publish report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
